apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: apifirst
build:
  artifacts:
    - image: iteam1337/apifirst
  
deploy:
  kubectl:
    manifests:
      - k8s/namespace.yaml
      - k8s/web.yaml
    flags:
      global:
        - --namespace=apifirst